blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"


urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace="blog")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Magazine/Blog Theme">
	<meta name="author" content="Bootlab">

  <title>Milo - Magazine/Blog Theme</title>

  <link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
      <div class="container">

        <button class="navbar-toggler order-2 order-md-1" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-tooggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Posts</a>
              <div class="dropdown-menu" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="post-image.html">Image</a>
                <a class="dropdown-item" href="post-video.html">Video</a>
              </div>
          </ul>
        </div>

        <a class="navbar-brand mx-auto order-1 order-md-3" href="index.html">Milø</a>

        <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                  <a class="dropdown-item" href="post-image.html">Signup</a>
                  <a class="dropdown-item" href="post-video.html">Login</a>
                </div>
              </li>
          </ul>
          <form class="form-inline" role="search">
            <input class="search js-search form-control form-control-rounded me-sm-2" type="text" title="Qidiruv.." placeholder="Qidiruv.." aria-label="Qidiruv">
          </form>
        </div>
      </div>
    </nav>
  </header>

  <main class="main pt-4">

    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">

          <article class="card mb-4">
            <header class="card-header text-center">
              <h1 class="card-title">Men Kimman?</h1>
            </header>
            <div class="card-body">

              <p><strong>Assalomu Alaykum meni ismim Bekhruz Familiyam Salimov.</strong></p>


              <img src="https://images.unsplash.com/flagged/photo-1573740144655-bbb6e88fb18a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dXNlcnxlbnwwfHwwfHx8MA%3D%3D" class="img-fluid mb-3" alt="I" />


              <p>Men Dasturlashga Qiziqaman va judaham ko'p bo'lgan saytlarni yasadim va mening bu saytimda siz ro'yxatdan o'tib o'zingizga yoqgan postni tanlab unga like❤ dislike comment✔ ham qo'shsangiz bo'ladi👌 saytim sizga yoqadi degan umidda man👍.</p>

            </div>
          </article><!-- /.card -->

        </div>
      </div>
    </div>

  </main>

  <footer class="site-footer bg-dark">
    <div class="container">

        </li>
      </ul>
      <div class="copy">
        &copy; Milo 2022<br />
        BARCHA HUQUQLAR HIMOYALANGAN
      </div>
    </div>
  </footer>

  <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Magazine/Blog Theme">
	<meta name="author" content="Bootlab">

  <title>Milo - Magazine/Blog Theme</title>

  <link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
      <div class="container">

        <button class="navbar-toggler order-2 order-md-1" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-tooggle" href="{% url 'blog:home' %}" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Posts</a>
              <div class="dropdown-menu" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="post-image.html">Rasm</a>
                <a class="dropdown-item" href="post-video.html">Video</a>
              </div>
            </li>
          </ul>
        </div>

        <a class="navbar-brand mx-auto order-1 order-md-3" href="index.html">Milø</a>

        <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                  <a class="dropdown-item" href="post-image.html">Signup</a>
                  <a class="dropdown-item" href="post-video.html">Login</a>
                </div>
              </li>
          </ul>
          <form class="form-inline" role="qidiruv">
            <input class="search js-search form-control form-control-rounded me-sm-2" type="text" title="Qidiruv.." placeholder="Qidiruv.." aria-label="Qidiruv">
          </form>
        </div>
      </div>
    </nav>
  </header>

{% block content %}
  
  <main class="">
  </main>

{% endblock %}

  <footer class="site-footer bg-dark">
    <div class="container">

        </li>
      </ul>
      <div class="copy">
        &copy; Milo 2022<br />
        BARCHA HUQUQLAR HIMOYALANGAN
      </div>
    </div>
  </footer>

  <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html'%}


{% block content %}

<div class="container">

    <div class="row">
      <div class="col-md-9">

        <div class="row">
          <div class="col-md-6">

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-09-26 20:00">26 october 2021</time></a> in <a href="page-category.html">Journey</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">How can we sing about love?</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/22.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-09-03 20:00">3 october 2021</time></a> in <a href="page-category.html">Lifestyle</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">Oh, I guess they have the blues</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/18.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-07-16 20:00">16 july 2021</time></a> in <a href="page-category.html">Work</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">How can we, how can we sing about ourselves?</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/12.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

          </div>
          <div class="col-md-6">

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-09-15 20:00">15 october 2021</time></a> in <a href="page-category.html">Lifestyle</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">The king is made of paper</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/5.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-08-24 20:00">24 august 2021</time></a> in <a href="page-category.html">Work</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">Crying on the news</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/13.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

            <article class="card mb-4">
              <header class="card-header">
                <div class="card-meta">
                  <a href="#"><time class="timeago" datetime="2021-05-08 20:00">8 may 2021</time></a> in <a href="page-category.html">Journey</a>
                </div>
                <a href="post-image.html">
                  <h4 class="card-title">How can you not sing about love?</h4>
                </a>
              </header>
              <a href="post-image.html">
                <img class="card-img" src="img/articles/1.jpg" alt="" />
              </a>
              <div class="card-body">
                <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
              </div>
            </article><!-- /.card -->

          </div>
        </div>

      </div>
      <div class="col-md-3 ms-auto">

        <aside class="sidebar">
          <div class="card mb-4">
            <div class="card-body">
              <h4 class="card-title">About</h4>
              <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam <a href="#">semper libero</a>, sit amet adipiscing sem neque sed ipsum. </p>
            </div>
          </div><!-- /.card -->
        </aside>

        <aside class="sidebar sidebar-sticky">
          <div class="card mb-4">
            <div class="card-body">
              <h4 class="card-title">Tags</h4>
              <a class="btn btn-light btn-sm mb-1" href="page-category.html">Journey</a>
              <a class="btn btn-light btn-sm mb-1" href="page-category.html">Work</a>
              <a class="btn btn-light btn-sm mb-1" href="page-category.html">Lifestype</a>
              <a class="btn btn-light btn-sm mb-1" href="page-category.html">Photography</a>
              <a class="btn btn-light btn-sm mb-1" href="page-category.html">Food & Drinks</a>
            </div>
          </div><!-- /.card -->
          <div class="card mb-4">
            <div class="card-body">
              <h4 class="card-title">Popular stories</h4>

              <a href="post-image.html" class="d-inline-block">
                <h4 class="h6">The blind man</h4>
                <img class="card-img" src="img/articles/2.jpg" alt="" />
              </a>
              <time class="timeago" datetime="2021-09-03 20:00">3 october 2021</time> in Lifestyle

              <a href="post-image.html" class="d-inline-block mt-3">
                <h4 class="h6">Crying on the news</h4>
                <img class="card-img" src="img/articles/3.jpg" alt="" />
              </a>
              <time class="timeago" datetime="2021-07-16 20:00">16 july 2021</time> in Work

            </div>
          </div><!-- /.card -->
        </aside>

      </div>
    </div>
  </div>


{% endblock %}